using GameCreator.Runtime.Characters;
using UnityEngine;
using System.Collections.Generic;
using BlockGeneration;
using Block = BlockGeneration.Block;

public class CityManager : MonoBehaviour
{
    [SerializeField] private CityGenerator cityGenerator;
    [SerializeField] private Character character;
    
    [Header("Character Positioning")]
    [SerializeField] private float characterHeightOffset = 2f;
    
    [Header("Character Settings")]
    [SerializeField] private float characterSpeed = 50f;
    
    [Header("Delivery Points")]
    [SerializeField] private bool autoGenerateDeliveryPoints = true;
    [SerializeField] private float deliveryPointHeight = 1f;
    [SerializeField] private float minDistanceBetweenPoints = 100f;
    [SerializeField] private int maxAttempts = 30;
    
    [Header("Game Time System")]
    [SerializeField] private float startHour = 9f;  // Начало рабочего дня (09:00)
    [SerializeField] private float endHour = 18f;   // Конец рабочего дня (18:00)
    [SerializeField] private float gameMinutesPerRealSecond = 1f; // Скорость течения времени
    [SerializeField] private bool loopTimeAfterEnd = true; // Зацикливать ли время после окончания дня
    
    public GameObject StartDeliveryPoint { get; private set; }
    public GameObject EndDeliveryPoint { get; private set; }
    
    // Свойства для доступа к текущему времени из других скриптов
    private float _currentTimeInMinutes;
    private bool _isTimePaused = false;
    
    /// <summary>
    /// Получить текущее время в часах (например, 14.5 означает 14:30)
    /// </summary>
    public float CurrentTimeInHours => _currentTimeInMinutes / 60f;
    
    /// <summary>
    /// Получить текущий час (целое число от 0 до 23)
    /// </summary>
    public int CurrentHour => Mathf.FloorToInt(_currentTimeInMinutes / 60f);
    
    /// <summary>
    /// Получить текущую минуту (целое число от 0 до 59)
    /// </summary>
    public int CurrentMinute => Mathf.FloorToInt(_currentTimeInMinutes % 60f);
    
    /// <summary>
    /// Получить текущую секунду (целое число от 0 до 59)
    /// </summary>
    public int CurrentSecond => Mathf.FloorToInt((_currentTimeInMinutes % 1f) * 60f);
    
    /// <summary>
    /// Проверить, идёт ли сейчас рабочее время (между startHour и endHour)
    /// </summary>
    public bool IsWorkingHours => CurrentTimeInHours >= startHour && CurrentTimeInHours < endHour;

    private void Start()
    {
        // Инициализируем время с начала рабочего дня
        _currentTimeInMinutes = startHour * 60f;
        
        if (cityGenerator != null)
        {
            cityGenerator.OnCityGenerationComplete += OnCityReady;
        }
    }

    private void Update()
    {
        // Обновляем игровое время каждый кадр
        UpdateGameTime();
    }

    private void OnDestroy()
    {
        if (cityGenerator != null)
        {
            cityGenerator.OnCityGenerationComplete -= OnCityReady;
        }
    }
    
    /// <summary>
    /// Обновляет внутриигровое время на основе реального времени
    /// </summary>
    private void UpdateGameTime()
    {
        if (_isTimePaused) return;
        
        // Увеличиваем время. gameMinutesPerRealSecond определяет, сколько игровых минут
        // проходит за одну реальную секунду. Time.deltaTime - это время с прошлого кадра.
        _currentTimeInMinutes += gameMinutesPerRealSecond * Time.deltaTime;
        
        // Проверяем, не достигли ли мы конца рабочего дня
        if (CurrentTimeInHours >= endHour)
        {
            if (loopTimeAfterEnd)
            {
                // Возвращаемся к началу рабочего дня
                _currentTimeInMinutes = startHour * 60f;
                Debug.Log("Working day ended, time reset to start of day");
            }
            else
            {
                // Останавливаем время на конце дня
                _currentTimeInMinutes = endHour * 60f;
                _isTimePaused = true;
                Debug.Log("Working day ended, time paused");
            }
        }
    }

    private void OnCityReady()
    {
        PlaceCharacterInCityCenter();
        SetupCharacterSpeed();
        
        if (autoGenerateDeliveryPoints)
        {
            CreateDeliveryPoints();
        }
        
        Debug.Log("City generation complete! Character and delivery points created.");
    }

    private void PlaceCharacterInCityCenter()
    {
        if (character == null) return;
        
        Vector3 cityCenter = new Vector3(0, characterHeightOffset, 0);
        character.transform.position = cityCenter;
        character.transform.rotation = Quaternion.identity;
    }

    private void SetupCharacterSpeed()
    {
        if (character == null || character.Motion == null) return;
        
        character.Motion.LinearSpeed = characterSpeed;
        Debug.Log($"Character speed set to: {characterSpeed}");
    }

    private void CreateDeliveryPoints()
    {
        if (cityGenerator == null) return;
        
        GameObject deliveryContainer = new GameObject("Delivery Points");
        
        StartDeliveryPoint = CreateDeliveryPoint(
            "Start Delivery Point", 
            deliveryContainer.transform,
            Color.green
        );
        
        EndDeliveryPoint = CreateDeliveryPoint(
            "End Delivery Point", 
            deliveryContainer.transform,
            Color.red
        );
        
        Vector3 startPos = GetPositionNearBuilding();
        Vector3 endPos = GetPositionNearBuilding();
        
        int attempts = 0;
        while (Vector3.Distance(startPos, endPos) < minDistanceBetweenPoints && attempts < maxAttempts)
        {
            endPos = GetPositionNearBuilding();
            attempts++;
        }
        
        StartDeliveryPoint.transform.position = startPos;
        EndDeliveryPoint.transform.position = endPos;
        
        Debug.Log($"Delivery points created near buildings: Start at {startPos}, End at {endPos}, Distance: {Vector3.Distance(startPos, endPos):F2}");
    }
    
    // === ПУБЛИЧНЫЕ МЕТОДЫ ДЛЯ УПРАВЛЕНИЯ ВРЕМЕНЕМ ===
    
    /// <summary>
    /// Установить конкретное время в формате часов (например, 12.5 = 12:30)
    /// </summary>
    public void SetTime(float hours)
    {
        _currentTimeInMinutes = hours * 60f;
        Debug.Log($"Time manually set to {hours:F2} hours ({CurrentHour}:{CurrentMinute:D2})");
    }
    
    /// <summary>
    /// Поставить время на паузу или возобновить его
    /// </summary>
    public void SetTimePaused(bool paused)
    {
        _isTimePaused = paused;
        Debug.Log($"Time {(paused ? "paused" : "resumed")} at {CurrentHour}:{CurrentMinute:D2}");
    }
    
    /// <summary>
    /// Сбросить время к началу рабочего дня
    /// </summary>
    public void ResetTime()
    {
        _currentTimeInMinutes = startHour * 60f;
        _isTimePaused = false;
        Debug.Log($"Time reset to start of working day: {startHour}:00");
    }
    
    /// <summary>
    /// Изменить скорость течения времени
    /// </summary>
    public void SetTimeSpeed(float minutesPerSecond)
    {
        gameMinutesPerRealSecond = minutesPerSecond;
        Debug.Log($"Time speed changed to {minutesPerSecond} game minutes per real second");
    }

    // === ВСЕ ОСТАЛЬНЫЕ МЕТОДЫ ОСТАЮТСЯ БЕЗ ИЗМЕНЕНИЙ ===

    private bool IsPositionWithinMapBounds(Vector3 position)
    {
        float halfMapSize = cityGenerator.mapSize / 2f;
        float safetyOffset = cityGenerator.mapSize * 0.1f;
        
        float minBound = -halfMapSize + safetyOffset;
        float maxBound = halfMapSize - safetyOffset;
        
        float unscaledX = position.x / cityGenerator.mapScale;
        float unscaledZ = position.z / cityGenerator.mapScale;
        
        bool isWithinBounds = unscaledX >= minBound && unscaledX <= maxBound &&
                              unscaledZ >= minBound && unscaledZ <= maxBound;
        
        if (!isWithinBounds)
        {
            Debug.LogWarning($"Position ({unscaledX:F2}, {unscaledZ:F2}) is outside safe map bounds [{minBound:F2}, {maxBound:F2}]");
        }
        
        return isWithinBounds;
    }

    private bool IsPointInsideBlock(Vector2 point, Block block)
    {
        if (block.Nodes == null || block.Nodes.Count < 3)
            return false;

        int intersectionCount = 0;
        int nodeCount = block.Nodes.Count;

        for (int i = 0; i < nodeCount; i++)
        {
            BlockNode node1 = block.Nodes[i];
            BlockNode node2 = block.Nodes[(i + 1) % nodeCount];

            Vector2 v1 = new Vector2(node1.X, node1.Y);
            Vector2 v2 = new Vector2(node2.X, node2.Y);

            if ((v1.y > point.y) != (v2.y > point.y))
            {
                float intersectionX = (v2.x - v1.x) * (point.y - v1.y) / (v2.y - v1.y) + v1.x;
                
                if (point.x < intersectionX)
                {
                    intersectionCount++;
                }
            }
        }

        return (intersectionCount % 2) == 1;
    }

    private float GetMinDistanceToBlock(Vector2 point, Block block)
    {
        float minDistance = float.MaxValue;
        
        foreach (var node in block.Nodes)
        {
            Vector2 nodePos = new Vector2(node.X, node.Y);
            float distance = Vector2.Distance(point, nodePos);
            if (distance < minDistance)
            {
                minDistance = distance;
            }
        }
        
        return minDistance;
    }

    private Vector3 GetPositionNearBuilding()
    {
        var lots = cityGenerator.GetLots();
        
        if (lots == null || lots.Count == 0)
        {
            Debug.LogWarning("No lots found, using random position on map");
            return GetRandomPositionOnMap();
        }
        
        int globalAttempts = 0;
        int maxGlobalAttempts = maxAttempts * 3;
        
        while (globalAttempts < maxGlobalAttempts)
        {
            Block selectedLot = null;
            int lotSelectionAttempts = 0;
            
            while ((selectedLot == null || selectedLot.IsPark) && lotSelectionAttempts < 50)
            {
                int randomLotIndex = Random.Range(0, lots.Count);
                selectedLot = lots[randomLotIndex];
                lotSelectionAttempts++;
            }
            
            if (selectedLot == null || selectedLot.Nodes == null || selectedLot.Nodes.Count == 0)
            {
                globalAttempts++;
                continue;
            }
            
            BlockNode randomNode = GetRandomNodeFromBlock(selectedLot);
            Vector3 nodePosition = new Vector3(randomNode.X, 0, randomNode.Y);
            
            Vector3 position = nodePosition;
            position.y = deliveryPointHeight;
            
            int validationAttempts = 0;
            bool foundValidPosition = false;
            
            while (validationAttempts < maxAttempts)
            {
                Vector2 position2D = new Vector2(position.x, position.z);
                bool isInsideAnyLot = false;
                
                foreach (var lot in lots)
                {
                    if (lot.IsPark) continue;
                    
                    if (IsPointInsideBlock(position2D, lot))
                    {
                        isInsideAnyLot = true;
                        break;
                    }
                }
                
                if (!isInsideAnyLot)
                {
                    float minDistance = GetMinDistanceToBlock(position2D, selectedLot);
                    if (minDistance >= 0)
                    {
                        Vector3 scaledPosition = new Vector3(
                            position.x * cityGenerator.mapScale,
                            position.y,
                            position.z * cityGenerator.mapScale
                        );
                        
                        if (IsPositionWithinMapBounds(scaledPosition))
                        {
                            foundValidPosition = true;
                            position = scaledPosition;
                            break;
                        }
                        else
                        {
                            Debug.Log($"Position rejected: outside map bounds");
                        }
                    }
                }
                
                position = nodePosition;
                position.y = deliveryPointHeight;
                validationAttempts++;
            }
            
            if (foundValidPosition)
            {
                Debug.Log($"Found valid position inside map bounds after {globalAttempts + 1} global attempts, {validationAttempts} validation attempts");
                return position;
            }
            
            globalAttempts++;
        }
        
        Debug.LogWarning("Could not find valid position near buildings, using safe random position");
        return GetSafeRandomPositionOnMap();
    }

    private BlockNode GetRandomNodeFromBlock(Block block)
    {
        if (block.Nodes == null || block.Nodes.Count == 0)
        {
            return null;
        }
        
        int randomIndex = Random.Range(0, block.Nodes.Count);
        return block.Nodes[randomIndex];
    }

    private GameObject CreateDeliveryPoint(string name, Transform parent, Color gizmoColor)
    {
        GameObject point = new GameObject(name)
        {
            transform =
            {
                parent = parent
            }
        };

        DeliveryPointMarker marker = point.AddComponent<DeliveryPointMarker>();
        marker.markerColor = gizmoColor;
        marker.markerSize = 2f;

        point.AddComponent<DeliveryPointVisual>();
        
        return point;
    }

    private Vector3 GetSafeRandomPositionOnMap()
    {
        float halfMapSize = cityGenerator.mapSize / 2f;
        float safetyOffset = cityGenerator.mapSize * 0.1f;
        
        float minBound = -halfMapSize + safetyOffset;
        float maxBound = halfMapSize - safetyOffset;
        
        float x = Random.Range(minBound, maxBound);
        float z = Random.Range(minBound, maxBound);
        
        Vector3 position = new Vector3(
            x * cityGenerator.mapScale,
            deliveryPointHeight,
            z * cityGenerator.mapScale
        );
        
        Debug.Log($"Generated safe random position: {position}, unscaled: ({x:F2}, {z:F2})");
        
        return position;
    }

    private Vector3 GetRandomPositionOnMap()
    {
        return GetSafeRandomPositionOnMap();
    }
}