using GameCreator.Runtime.Characters;
using UnityEngine;
using System.Collections.Generic;
using BlockGeneration;
using Block = BlockGeneration.Block;

public class CityManager : MonoBehaviour
{
    [SerializeField] private CityGenerator cityGenerator;
    [SerializeField] private Character character;
    
    [Header("Character Positioning")]
    [SerializeField] private float characterHeightOffset = 2f;
    
    [Header("Character Settings")]
    [SerializeField] private float characterSpeed = 50f;
    
    [Header("Delivery Points")]
    [SerializeField] private bool autoGenerateDeliveryPoints = true;
    [SerializeField] private float deliveryPointHeight = 1f;
    [SerializeField] private float minDistanceBetweenPoints = 100f;
    [SerializeField] private int maxAttempts = 30; // Максимум попыток найти подходящую позицию
    
    public GameObject StartDeliveryPoint { get; private set; }
    public GameObject EndDeliveryPoint { get; private set; }

    private void Start()
    {
        if (cityGenerator != null)
        {
            cityGenerator.OnCityGenerationComplete += OnCityReady;
        }
    }

    private void OnDestroy()
    {
        if (cityGenerator != null)
        {
            cityGenerator.OnCityGenerationComplete -= OnCityReady;
        }
    }

    private void OnCityReady()
    {
        PlaceCharacterInCityCenter();
        SetupCharacterSpeed();
        
        if (autoGenerateDeliveryPoints)
        {
            CreateDeliveryPoints();
        }
        
        Debug.Log("City generation complete! Character and delivery points created.");
    }

    private void PlaceCharacterInCityCenter()
    {
        if (character == null) return;
        
        Vector3 cityCenter = new Vector3(0, characterHeightOffset, 0);
        character.transform.position = cityCenter;
        character.transform.rotation = Quaternion.identity;
    }

    private void SetupCharacterSpeed()
    {
        if (character == null || character.Motion == null) return;
        
        character.Motion.LinearSpeed = characterSpeed;
        Debug.Log($"Character speed set to: {characterSpeed}");
    }

    private void CreateDeliveryPoints()
    {
        if (cityGenerator == null) return;
        
        // Создаем контейнер для точек доставки
        GameObject deliveryContainer = new GameObject("Delivery Points");
        
        // Создаем начальную точку
        StartDeliveryPoint = CreateDeliveryPoint(
            "Start Delivery Point", 
            deliveryContainer.transform,
            Color.green
        );
        
        // Создаем конечную точку
        EndDeliveryPoint = CreateDeliveryPoint(
            "End Delivery Point", 
            deliveryContainer.transform,
            Color.red
        );
        
        // Размещаем точки возле зданий
        Vector3 startPos = GetPositionNearBuilding();
        Vector3 endPos = GetPositionNearBuilding();
        
        // Проверяем, что точки не слишком близко друг к другу
        int attempts = 0;
        while (Vector3.Distance(startPos, endPos) < minDistanceBetweenPoints && attempts < maxAttempts)
        {
            endPos = GetPositionNearBuilding();
            attempts++;
        }
        
        StartDeliveryPoint.transform.position = startPos;
        EndDeliveryPoint.transform.position = endPos;
        
        Debug.Log($"Delivery points created near buildings: Start at {startPos}, End at {endPos}, Distance: {Vector3.Distance(startPos, endPos):F2}");
    }

    /// <summary>
    /// Проверяет, находится ли позиция в безопасной зоне карты (с отступом от краев)
    /// </summary>
    private bool IsPositionWithinMapBounds(Vector3 position)
    {
        // Вычисляем границы карты с учетом отступа (ДО применения масштаба)
        float halfMapSize = cityGenerator.mapSize / 2f;
        float safetyOffset = cityGenerator.mapSize * 0.1f;
        
        float minBound = -halfMapSize + safetyOffset;
        float maxBound = halfMapSize - safetyOffset;
        
        // Проверяем позицию ДО масштабирования
        float unscaledX = position.x / cityGenerator.mapScale;
        float unscaledZ = position.z / cityGenerator.mapScale;
        
        bool isWithinBounds = unscaledX >= minBound && unscaledX <= maxBound &&
                              unscaledZ >= minBound && unscaledZ <= maxBound;
        
        if (!isWithinBounds)
        {
            Debug.LogWarning($"Position ({unscaledX:F2}, {unscaledZ:F2}) is outside safe map bounds [{minBound:F2}, {maxBound:F2}]");
        }
        
        return isWithinBounds;
    }

    /// <summary>
    /// Алгоритм Ray Casting для проверки, находится ли точка внутри полигона
    /// </summary>
    private bool IsPointInsideBlock(Vector2 point, Block block)
    {
        if (block.Nodes == null || block.Nodes.Count < 3)
            return false;

        int intersectionCount = 0;
        int nodeCount = block.Nodes.Count;

        for (int i = 0; i < nodeCount; i++)
        {
            BlockNode node1 = block.Nodes[i];
            BlockNode node2 = block.Nodes[(i + 1) % nodeCount];

            Vector2 v1 = new Vector2(node1.X, node1.Y);
            Vector2 v2 = new Vector2(node2.X, node2.Y);

            // Проверяем, пересекает ли луч от точки вправо ребро полигона
            if ((v1.y > point.y) != (v2.y > point.y))
            {
                float intersectionX = (v2.x - v1.x) * (point.y - v1.y) / (v2.y - v1.y) + v1.x;
                
                if (point.x < intersectionX)
                {
                    intersectionCount++;
                }
            }
        }

        // Если количество пересечений нечетное, точка внутри полигона
        return (intersectionCount % 2) == 1;
    }

    /// <summary>
    /// Проверяет минимальное расстояние от точки до любого узла блока
    /// </summary>
    private float GetMinDistanceToBlock(Vector2 point, Block block)
    {
        float minDistance = float.MaxValue;
        
        foreach (var node in block.Nodes)
        {
            Vector2 nodePos = new Vector2(node.X, node.Y);
            float distance = Vector2.Distance(point, nodePos);
            if (distance < minDistance)
            {
                minDistance = distance;
            }
        }
        
        return minDistance;
    }

    private Vector3 GetPositionNearBuilding()
    {
        // Получаем доступ к лотам (зданиям)
        var lots = cityGenerator.GetLots();
        
        if (lots == null || lots.Count == 0)
        {
            Debug.LogWarning("No lots found, using random position on map");
            return GetRandomPositionOnMap();
        }
        
        // Пытаемся найти валидную позицию несколько раз
        int globalAttempts = 0;
        int maxGlobalAttempts = maxAttempts * 3;
        
        while (globalAttempts < maxGlobalAttempts)
        {
            // Выбираем случайное здание (не парк)
            Block selectedLot = null;
            int lotSelectionAttempts = 0;
            
            while ((selectedLot == null || selectedLot.IsPark) && lotSelectionAttempts < 50)
            {
                int randomLotIndex = Random.Range(0, lots.Count);
                selectedLot = lots[randomLotIndex];
                lotSelectionAttempts++;
            }
            
            if (selectedLot == null || selectedLot.Nodes == null || selectedLot.Nodes.Count == 0)
            {
                globalAttempts++;
                continue;
            }
            
            // Находим случайный узел здания для размещения точки
            BlockNode randomNode = GetRandomNodeFromBlock(selectedLot);
            Vector3 nodePosition = new Vector3(randomNode.X, 0, randomNode.Y);
            
            // Размещаем точку снаружи от узла
            Vector3 position = nodePosition;
            position.y = deliveryPointHeight;
            
            // Проверяем что точка не внутри ЛЮБОГО лота
            int validationAttempts = 0;
            bool foundValidPosition = false;
            
            while (validationAttempts < maxAttempts)
            {
                Vector2 position2D = new Vector2(position.x, position.z);
                bool isInsideAnyLot = false;
                
                // Проверяем все лоты
                foreach (var lot in lots)
                {
                    if (lot.IsPark) continue; // Пропускаем парки
                    
                    if (IsPointInsideBlock(position2D, lot))
                    {
                        isInsideAnyLot = true;
                        break;
                    }
                }
                
                if (!isInsideAnyLot)
                {
                    // Дополнительная проверка - точка должна быть на минимальном расстоянии от здания
                    float minDistance = GetMinDistanceToBlock(position2D, selectedLot);
                    if (minDistance >= 0)
                    {
                        // Применяем масштаб карты для финальной проверки
                        Vector3 scaledPosition = new Vector3(
                            position.x * cityGenerator.mapScale,
                            position.y,
                            position.z * cityGenerator.mapScale
                        );
                        
                        // КРИТИЧЕСКАЯ ПРОВЕРКА: позиция в пределах карты
                        if (IsPositionWithinMapBounds(scaledPosition))
                        {
                            foundValidPosition = true;
                            position = scaledPosition;
                            break;
                        }
                        else
                        {
                            Debug.Log($"Position rejected: outside map bounds");
                        }
                    }
                }
                
                // Если не нашли валидную позицию, пробуем другой узел
                position = nodePosition;
                position.y = deliveryPointHeight;
                validationAttempts++;
            }
            
            if (foundValidPosition)
            {
                Debug.Log($"Found valid position inside map bounds after {globalAttempts + 1} global attempts, {validationAttempts} validation attempts");
                return position;
            }
            
            globalAttempts++;
        }
        
        // Если не нашли позицию возле здания, используем fallback с проверкой границ
        Debug.LogWarning("Could not find valid position near buildings, using safe random position");
        return GetSafeRandomPositionOnMap();
    }

    private BlockNode GetRandomNodeFromBlock(Block block)
    {
        if (block.Nodes == null || block.Nodes.Count == 0)
        {
            return null;
        }
        
        int randomIndex = Random.Range(0, block.Nodes.Count);
        return block.Nodes[randomIndex];
    }

    private GameObject CreateDeliveryPoint(string name, Transform parent, Color gizmoColor)
    {
        GameObject point = new GameObject(name)
        {
            transform =
            {
                parent = parent
            }
        };

        // Добавляем компонент для визуализации
        DeliveryPointMarker marker = point.AddComponent<DeliveryPointMarker>();
        marker.markerColor = gizmoColor;
        marker.markerSize = 2f;

        point.AddComponent<DeliveryPointVisual>();
        
        return point;
    }

    /// <summary>
    /// Генерирует случайную позицию на карте с учетом безопасных границ
    /// </summary>
    private Vector3 GetSafeRandomPositionOnMap()
    {
        float halfMapSize = cityGenerator.mapSize / 2f;
        float safetyOffset = cityGenerator.mapSize * 0.1f;
        
        // Вычисляем безопасные границы ДО масштабирования
        float minBound = -halfMapSize + safetyOffset;
        float maxBound = halfMapSize - safetyOffset;
        
        // Генерируем случайную позицию в безопасной зоне
        float x = Random.Range(minBound, maxBound);
        float z = Random.Range(minBound, maxBound);
        
        // Применяем масштаб
        Vector3 position = new Vector3(
            x * cityGenerator.mapScale,
            deliveryPointHeight,
            z * cityGenerator.mapScale
        );
        
        Debug.Log($"Generated safe random position: {position}, unscaled: ({x:F2}, {z:F2})");
        
        return position;
    }

    /// <summary>
    /// Старый метод GetRandomPositionOnMap - оставлен для совместимости, но теперь использует безопасные границы
    /// </summary>
    private Vector3 GetRandomPositionOnMap()
    {
        return GetSafeRandomPositionOnMap();
    }
}